# Generated by Django 4.2.5 on 2023-09-07 13:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Say Something nice', max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('intro_text', models.TextField()),
                ('image_url', models.ImageField(upload_to='AboutUs/%y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='ApointmentContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Appoint_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length='150')),
                ('contact_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carousel/%y/%m/%d/')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day1', models.CharField(default='Mon - Fri', max_length=20)),
                ('hours1', models.CharField(max_length=50)),
                ('day2', models.CharField(max_length=20)),
                ('hours2', models.CharField(max_length=50)),
                ('day3', models.CharField(max_length=20)),
                ('hours3', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image_url', models.ImageField(upload_to='Service/%y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Team/%y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('testimonial_text', models.TextField()),
                ('image_url', models.ImageField(upload_to='Testimonial/%y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=30, null=True, unique=True)),
                ('comfirm_password', models.CharField(max_length=30, null=True, unique=True)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('gender', models.CharField(choices=[('Gender', 'Gender'), ('Female', 'Female'), ('Male', 'Male')], max_length=90, null=True)),
                ('admission_number', models.CharField(max_length=20, null=True)),
                ('maritalstat', models.CharField(choices=[('Select', 'Select'), ('Gender', 'Gender'), ('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], max_length=100, null=True)),
                ('qualification', models.CharField(choices=[('Select', 'Select'), ('Doctor', 'Doctor'), ('Nurse', 'Nurse'), ('Pharmacist', 'Pharmacist'), ('Consultant', 'Consultant'), ('Laboratory', 'Laboratory')], max_length=30, null=True)),
                ('Services_Rendered', models.TextField(max_length=250, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('allergies', models.TextField(null=True)),
                ('medical_condition', models.TextField(null=True)),
                ('taking_medications', models.BooleanField(null=True)),
                ('medications', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=30, null=True, unique=True)),
                ('comfirm_password', models.CharField(max_length=30, null=True, unique=True)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('gender', models.CharField(choices=[('Gender', 'Gender'), ('Female', 'Female'), ('Male', 'Male')], max_length=90, null=True)),
                ('maritalstat', models.CharField(choices=[('Select', 'Select'), ('Gender', 'Gender'), ('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], max_length=100, null=True)),
                ('faculty', models.CharField(choices=[('Faculty', 'Faculty'), ('Faculty of Science', 'Faculty of Science'), ('Faculty of Arts and Management Science', 'Faculty of Arts and Management Science'), ('Faculty of Law', 'Faculty of Law')], max_length=200, null=True)),
                ('department', models.CharField(choices=[('Select', 'Select'), ('Department of Biology and Forensic Science', 'Department of Biology and Forensic Science'), ('Department of Computing Science', 'Department of Computing Science'), ('Department of Public Law and Private Law', 'Department of Public Law and Private Law'), ('Department of Accounting/Business Administration/Economics', 'Department of Accounting/Business Administration/Economics'), ('Department of English & Literary Studies/History & International Studies', 'Department of English & Literary Studies/History & International Studies'), ('Department of International Relations/Hospitality & Tourism Studies', 'Department of International Relations/Hospitality & Tourism Studies')], max_length=100, null=True)),
                ('admission_number', models.CharField(max_length=20, null=True)),
                ('room_number', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000)])),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('allergies', models.TextField(null=True)),
                ('medical_condition', models.TextField(null=True)),
                ('taking_medications', models.BooleanField(null=True)),
                ('medications', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
