# Generated by Django 2.2.6 on 2023-09-10 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adun', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffregistration',
            name='Services_Rendered',
        ),
        migrations.RemoveField(
            model_name='staffregistration',
            name='admission_number',
        ),
        migrations.RemoveField(
            model_name='staffregistration',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='staffregistration',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='staffregistration',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='staffregistration',
            name='height',
        ),
        migrations.RemoveField(
            model_name='staffregistration',
            name='maritalstat',
        ),
        migrations.RemoveField(
            model_name='staffregistration',
            name='medical_condition',
        ),
        migrations.RemoveField(
            model_name='staffregistration',
            name='medications',
        ),
        migrations.RemoveField(
            model_name='staffregistration',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='staffregistration',
            name='taking_medications',
        ),
        migrations.RemoveField(
            model_name='staffregistration',
            name='user',
        ),
        migrations.RemoveField(
            model_name='staffregistration',
            name='weight',
        ),
        migrations.AddField(
            model_name='staffregistration',
            name='staff_user',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='apointmentcontent',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='appoint_contact',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='carouselitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='patientregistration',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='patientregistration',
            name='user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='staffregistration',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='staffregistration',
            name='qualification',
            field=models.CharField(choices=[('Select', 'Select'), ('Doctor', 'Doctor'), ('Nurse', 'Nurse'), ('Pharmacist', 'Pharmacist'), ('Consultant', 'Consultant'), ('Laboratory', 'Laboratory')], default='Select', max_length=100),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
