# Generated by Django 2.2.6 on 2023-09-10 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adun', '0002_auto_20230910_0357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffregistration',
            old_name='staff_user',
            new_name='Id_number',
        ),
    ]
