# Generated by Django 2.2.6 on 2023-09-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adun', '0003_auto_20230910_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffregistration',
            name='Id_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
