# Generated by Django 2.2.6 on 2023-09-11 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adun', '0005_auto_20230910_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientregistration',
            name='matric_num',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
