# Generated by Django 2.2.6 on 2023-09-11 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adun', '0006_patientregistration_matric_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientregistration',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
