# Generated by Django 2.2.6 on 2023-09-11 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adun', '0007_auto_20230911_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientregistration',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
